# Generated by Django 3.1.1 on 2020-09-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Active'), ('O', 'On Hold'), ('R', 'Resolved'), ('C', 'Closed')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Active'), ('O', 'On Hold'), ('R', 'Resolved'), ('C', 'Closed')], default='N', max_length=1),
        ),
    ]
