# Generated by Django 3.1.1 on 2020-09-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0002_auto_20200922_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=8),
        ),
    ]
