# Generated by Django 3.1.1 on 2020-10-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Task', 'Task')], default='Bug', max_length=4),
        ),
    ]
